name: Deploy Node.js Application to Amazon EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: nodejs-demo
  EKS_CLUSTER_NAME: pipeline-eks-cluster
  AWS_ACCOUNT_ID: 949228373261

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:

      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY .

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Push Docker Image to Amazon ECR
      - name: Push Docker Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Configure kubectl for EKS
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

      # Deploy Kubernetes Resources
      - name: Deploy to Amazon EKS
        run: |
          kubectl apply -f terraform/deployment.yaml
          kubectl apply -f terraform/service.yaml
          kubectl apply -f terraform/ingress.yaml

      # Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
